### ISSUE TITLE
Details about users.json

### ISSUE THREAD

**Issue by Gakamine** [RblSb/SyncTube#10]
Hello, I would like to manage permissions for users and I saw in the documentation we could do it by creating users.json in /user but there is no detail or example about how the data has to be stored in.
Thank you in advance :)

**Comment by RblSb** [comment]
Hi, there is only limited way to make admin users from server side:
After run `node build/server.js` you can use commands in console, like:
`/addAdmin Asuka 1234`
This will create `user/users.json` file like:
```json
{
	"admins": [
		{
			"name": "Asuka",
			"hash": "c4eb156bee15ccafe7f7d898df11b33642cbb291783916f6ed45d151956d6813"
		}
	],
	"salt": "1c3106debf5d929db1b509ee29de81939a7ba8ca6e51fcf7e8a49c293e44b8ca"
}
```
If you don't want to use console, same json file can be written manually before server started, "admins" items is [very simple to generate](https://try.haxe.org/#76305).
After admin created you can login as `Asuka` with `1234` password on client to have admin permissions. Default permissions are inside `default-config.json`:
```json
"permissions": {
	"guest": ["writeChat", "addVideo", "removeVideo", "changeOrder", "requestLeader", "rewind"],
	"user": ["guest"],
	"leader": ["user"],
	"admin": ["user", "clearChat", "setLeader", "lockPlaylist"]
},
```
(`"user": ["guest"]` is like `User extends Guest`)
You can create such `{"permissions": {...}}` field in `user/config.json` and move strings around between user groups.
Let me know if you have questions or not-too-big feature requests =)

**Comment by Gakamine** [comment]
Thank you for your quick answer!
SyncTube already has everything I need to be honest :smiley:
