### ISSUE TITLE
Only 50 Videos at once?

### ISSUE THREAD

**Issue by leThrax** [RblSb/SyncTube#12]
I've looked a bit through the code and it appeared that the amount of videos you can add at once is hardcoded at 50 for now. 
At least trying to edit the config didn't change anything, the max limit of added videos is 50. 
Is there a way around? I have several music playlists with 50+ songs and it would come in handy since it's only adding the first 50 of those playlists.

**Comment by RblSb** [comment]
`{"youtubePlaylistLimit": 200}` in `user/config.json` should do the job. You also can be interested to set personal [youtubeApiKey](https://www.slickremix.com/docs/get-api-key-for-youtube/) property here, if default key quota will be exceeded.

**Comment by leThrax** [comment]
I've tried adjusting the config and it's working perfectly fine values like 20 or 40, just everything above 50 though is not working at all. I edited the `default-config.json` as well as the `user/config.json`. 

I've also added my own personal YouTube API key.

**Comment by RblSb** [comment]
Overconfidence is insidious killer. Check latest commit.

**Comment by leThrax** [comment]
Updating it wasn't working for me yet. 
I tried reinstalling it again, now I sadly get and `uncaughtException` when I try to build the server.

**Comment by RblSb** [comment]
If you get local ip in console and exception on next line: i think this happens when you try to run synctube on already used port (like if port already in use by synctube or other server app). Can you check is this true and try to kill `node` process?

**Comment by leThrax** [comment]
ahhh yeah that was the mistake, everything's working perfect now, I can finally add more than 50 videos. Thank you a lot!

**Comment by RblSb** [comment]
No problem. Also added warning + port increment instead of crash for this case.
