### ISSUE TITLE
Add QOL features

### ISSUE THREAD

**Issue by Sublimeful** [RblSb/SyncTube#17]
I would really like to see some QOL features on this. I really think this is one of the best synctube-like apps out there. But it's missing some features that I feel would enhance the user experience, such as:
- Ability to change the title of the media you add
- Add and delete emotes on the fly (Like in cytube)
- Ability to add subtitles to videos
I've already implemented some of these features on my fork. But I would really like these features to be on the main repository.
Please and thank you.

**Comment by RblSb** [comment]
Thanks, i added media title input. About emotes, this requires more work, like edit mode with simple way to change, remove and reorder items, i think only add/remove alerts are not useful enough as gui. Maybe it can fits better as server and client chat `/addEmote,` `/removeEmote` commands. Also, as you are using heroku, i need to mention that not commited changes by client/server are removed every day, so such feature only useful for personal servers.

About subtitles, there is ass plugin that is too big/experimental to have out of box, but it can be polished for simpler installation and more features, depending on use cases.

**Comment by Sublimeful** [comment]
Thank you so much! Yea, I am aware of the Heroku thing, so I'm looking into different options. And as for the subtitles plugin, are you perhaps referring to octosubs? If so then I will try to look into it and see what I can do with it.

**Comment by RblSb** [comment]
Yes, i mean the question is what you want from octosubs. If additional url input to ass file would be good enough for you, i can try to complete that plugin.

**Comment by Sublimeful** [comment]
Yes, that would be great! Also, thank you for suggesting the `/addEmote` and `/removeEmote` commands, I'm working on implementing them on my server right now!
