### ISSUE TITLE
MP4 Browser Playback Issue

### ISSUE THREAD

**Issue by Ruben-C** [RblSb/SyncTube#18]
From testing with several people and personal computers.  If I play a MP4 file and am using Edge or Safari everything works as expected.  For those watching using Chrome or Firefox the audio is muted and volume grayed out from media player.  Having people swap over to Edge does fix it for them.

**Comment by RblSb** [comment]
With Chrome and Firefox you need to click Play button to unmute/unpause video for first time. But if your problem with thing like audio is shown as not even existing in video container (but video played correctly in new tab) - i cannot reproduce it, so need to know OS name, browser version and any broken mp4 link ([or this can be tested](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4)). Also errors from chrome dev console would be nice (by pressing Shift + CTRL + J on synctube page)
