### ISSUE TITLE
google drive video support

### ISSUE THREAD

**Issue by duigIdc** [RblSb/SyncTube#19]
Is there any way to add google drive video support like in cytube using some kind of plugin?

**Comment by RblSb** [comment]
Tried to implement this integration today, but seems like cytube google drive userscript doesn't work anymore for multiple people and video link bound to ip or google account (https://github.com/calzoneman/sync/issues/896).
As alternative, you can download file, run synctube locally with open port to global network for other people and just add `/absolute/file/path/downloads/somefile.mp4` to playlist.
