### ISSUE TITLE
Chat not connecting

### ISSUE THREAD

**Issue by SuperSandro2000** [RblSb/SyncTube#2]
The chat on the left does not connect for me and throws the following error in the dev console.

````
client.js:871 WebSocket connection to 'wss://synctube-example.herokuapp.com:80/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
````

I tested it with Chrome 80.0.3987.149 on https://synctube-example.herokuapp.com/

**Comment by RblSb** [comment]
Hello, sadly heroku does not have free SSL support for WebSocket protocol:
https://devcenter.heroku.com/articles/websocket-security#wss
So demo is only working on http. Https still should works for other hosting services or heroku paid plans.

**Comment by losuler** [comment]
I had the same issue using a reverse proxy in Caddy, but I noticed that this commit https://github.com/llndqvst/SyncTube/commit/85145fc40c63137c1e08f6abb873f9472f2a8572 from a fork fixed it for me on this master.

**Comment by RblSb** [comment]
@losuler thank you for hint. At first, I thought that Heroku needs 433 port for wss here, but it seems that he doesn’t like ports at all.
