### ISSUE TITLE
Add an option to disable or restrtict "Quene Next" button to certain users

### ISSUE THREAD

**Issue by zneix** [RblSb/SyncTube#21]
Hi, we have our selfhosted SyncTube instance, but we often encounter some people abusing `Queue Next` button, so we would love to get rid of it, thanks!

![](https://cdn.zneix.eu/rJGFTKu.png)

**Comment by RblSb** [comment]
There is `changeOrder` permission, i think `Queue next` button can be disabled for users who don't have it, thoughts?

**Comment by zneix** [comment]
Excellent! that's exactly what we needed, and the commit you've made made it work as we wanted, thanks :heart:
