### ISSUE TITLE
[Feature Request] kick or ban users

### ISSUE THREAD

**Issue by siren15** [RblSb/SyncTube#26]
Is it possible to have kick or ban options or chat commands for admins? As if I use this for larger public events where there might be anonymous people and they don't behave, do things like spam etc, it would be neat to have some moderation features like this.

**Comment by RblSb** [comment]
Will try to implement ip-based (i think?) bans and "blocked" group in free time, chat commands should be fine for start. Also need some badges in userlist to show blocked users.

**Comment by siren15** [comment]
Thank you! 😄

**Comment by RblSb** [comment]
Let me know if this thing is not good enough.
