### ISSUE TITLE
Allow to have different client urls still synced

### ISSUE THREAD

**Issue by luckydonald** [RblSb/SyncTube#27]
So the problem is I want to use a webservice which is serving the mp4 files on a different url for each connecting IP (each client).

Is there some way to enter a different movie url on each client (basically overwrite the server's url),
but still use the playback sync?

**Comment by RblSb** [comment]
Can you describe some example of usecase?
I've been only thinking about button to change video url locally (on client-side by user yourself), to local file or video url with different quality/audio and same duration.

**Comment by luckydonald** [comment]
Yeah basically it's for those shady video sizes.
They server different urls for each user, so we can't all watch the "same" link as it's never the same.

Having the option to use a local file would work as well.

**Comment by RblSb** [comment]
Let me know if new gear buttons work for you
