### ISSUE TITLE
subtitles dont show

### ISSUE THREAD

**Issue by chia-gesundheit** [RblSb/SyncTube#28]
I saved subs.srt in the same folder as the movie.mp4 and start it with /d/movie.mp4 and /d/subs.srt
The button to enable/disable the subs in the bottom right shows but when it wont show any subs on the screen.
I also converted the subs to .ass but same problem occurs.
I tested the subs with VLC Player to confirm its not a broken file.

**Comment by chia-gesundheit** [comment]
tried edge/chrome and firefox

**Comment by RblSb** [comment]
Do you add subs from http/s url, from file system path, or host files inside `user/res` folder? Also would be nice to get link to unworked subs file or subs file in zip here.

**Comment by chia-gesundheit** [comment]
I add them from Downloads folder but its linked to the user/res folder. I can play any video by doing /d/movie.mp4 and the Subs are also in the Downloads folder but it doesnt work when i do /d/subs.srt. The original subs file works on VLC player heres the link [https://dl.opensubtitles.org/en/download/file/1956811931](url)

**Comment by chia-gesundheit** [comment]
I did a fresh install and im Up to date now with your fix but its the same as before. The Subtitles Options shows up (either .srt or .ass) and i can chose or unchose it but there aren't any subs showing on the screen.

**Comment by RblSb** [comment]
Hmm, can you check if problem exist when you connect from same ip as server? Try to run server and open `your synctube page ip/d/subs.srt` link, it should download actual file for you. Or this should download file with error message or show some empty/bad page. And try same link to subs from different ip.
I tried to add `/d/movie.mp4` and `/d/subs.srt` to playlist and i see subs on 6th second.
You can also open firefox developer tools (or any other browser), select network tab and check what is subs file status after you add item to playlist, refresh page and filter things:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8753432/129493273-0ba0189d-1ed4-421c-88a3-76f6d1c8c7fe.png">

**Comment by chia-gesundheit** [comment]
I can download the .srt file from the server locally or from an external device when i enter IP-adress/d/subs.srt . Theres no error and its a healthy file.
It just doesnt show any subtiles in the video, not when i try it in a browser on the local ubuntu server (firefox) and not externally in chrome or firefox. 
I also checked the network tab in firefox dev tools. it shows the subs file the same as in your screenshot.

**Comment by RblSb** [comment]
Still have no idea sadly, but i done `SyncTube/res/client.js` file with more debug traces, try to rename original and replace that file to this:
[client.js.zip](https://github.com/RblSb/SyncTube/files/7005670/client.js.zip)

Do you see subs in first four seconds if you add video with this subs url?
https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt

And same question about such subs url (6th second):
http://82.146.45.136/files/subs.srt

And after you add video item with `subs.srt` (not `vtt` one), open browser console, do you see subs content in it or some errors?

**Comment by RblSb** [comment]
Nevermind, i think i found problem place and solution for chromium-based browsers on Linux. In Firefox there is more complicated system-depending bug, and i dont have Linux host currently to debug it without random guesses, but will try little more with my linux-friend. Ehh, worst type of bugs, what a mess.

**Comment by chia-gesundheit** [comment]
Thanks for all the ideas firstly. 
I tried the new client.js but no changes.
I tried both urls as subs and they show in the lower right as recognised but there are again zero subs actually showing.
When i add the .srt subs i can see in the browser console under networks the healthy .srt file with no errors but under console i get the following error "Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. client.js:2788:27".
I also tried all the advice on the test site https://synctube-example.herokuapp.com/. But i dont know if it is up to date. Again no subs showing in the video.
Now I just randomly tested it again with chrome and it WORKED. I tested chrome before when i reported the problem but not afterwards..

**Comment by chia-gesundheit** [comment]
> 
> 
> Nevermind, i think i found problem place and solution for chromium-based browsers on Linux. In Firefox there is more complicated system-depending bug, and i dont have Linux host currently to debug it without random guesses, but will try little more with my linux-friend. Ehh, worst type of bugs, what a mess.

You seem to have already fixed it for chromium based browsers, thanks alot!! I can use chrome now but would still be interesting why firefox wont work haha.
