### ISSUE TITLE
uncaughtException: The argument 'path' must be a string or Uint8Array without null bytes.

### ISSUE THREAD

**Issue by SCP-155** [RblSb/SyncTube#30]
My publicly accessible instance of SyncTube just got scanned and "attacked" by bots. The bots tried a lot of known security flaws. One of them leads to the complete crashing of the SyncTube Server.

Log from SyncTube after crashing:
```Client USERNAME disconnected
uncaughtException, {
        message : The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/myuser/SyncTube/build/../res/skins/default.php?dir_inc=/etc/passwd\u0000',
        stack : TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/myuser/SyncTube/build/../res/skins/default.php?dir_inc=/etc/passwd\u0000'
    at Object.readFile (fs.js:296:3)
    at Function.server_HttpServer.serveFiles (/home/myuser/SyncTube/build/server.js:3618:13)
    at Server.<anonymous> (/home/myuser/SyncTube/build/server.js:3888:22)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:691:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
}
Saving state...
```

I have an nginx as proxy between the SyncTube Server and the web. Its URL therefore is `mydomain.de/video/`. 
Nginx just routes internal to http://127.0.0.1:4200/

So here are the NGINX Logs
Error Log:
```
[error] 59161#59161: *151083 upstream prematurely closed connection while reading response header from upstream, client: 34.107.118.5, server: mydomain.de, request: "GET /video/skins/default.php?dir_inc=/etc/passwd%00 HTTP/1.1", upstream: "http://127.0.0.1:4200/skins/default.php?dir_inc=/etc/passwd%00", host: "mydomain.de"
```

Access Log:
```
34.107.118.5 - - "GET /video/skins/default.php?dir_inc=/etc/passwd%00 HTTP/2.0" 502 3972 "-" "cyberscan.io"
```

**So shortly:** 
URL to reproduce: `http://IP:4200/skins/default.php?dir_inc=/etc/passwd%00` 
or simply adding `/skins/default.php?dir_inc=/etc/passwd%00`
That will break the server and forcing him to stop.

Is this an issue with SyncTube? Can it be fixed within SynTube, or is it at the nginx site to negotiate?

**Comment by RblSb** [comment]
Thanks for report, interesting case, let me know if there is other successful crashes.
