### ISSUE TITLE
youtube age restriction

### ISSUE THREAD

**Issue by Wunderharke** [RblSb/SyncTube#33]
Is there a way for youtube videos to be played if they are restricted to logged in users? Like the server and/or clients using youtube cookies to allow to play those videos?

**Comment by RblSb** [comment]
I don't think so, since youtube applied age restrictions to iframe player, there is no good way to get worked video player on web platform for such videos. You can only reupload that video without restrictions to other channel or some http server and then add `mp4` url to playlist.

**Comment by RblSb** [comment]
Added some way, more info in https://github.com/RblSb/SyncTube/issues/59#issuecomment-2660690250
