### ISSUE TITLE
package-lock.json error

### ISSUE THREAD

**Issue by flaxplax** [RblSb/SyncTube#34]
I get a lock file error when running the ```npm install ws```
```
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
```

**Comment by RblSb** [comment]
This is warning, so your `ws` installation should be fine. If you want you can remove local `node_modules` folder from project folder and rerun `npm install ws` again.
