### ISSUE TITLE
The server seems not handle query string properly

### ISSUE THREAD

**Issue by newlix** [RblSb/SyncTube#35]
When I shared the link http://synctube-example.herokuapp.com/ on my Facebook page and I clicked the link, Facebook redirect me back to
http://synctube-example.herokuapp.com/?fbclid=IwAR2Tj_sFrN8ks9n72wC0CkCYoPZQI7crWsfrqIKvEAMpPF6fmn2pqDhUKhA .

The server didn't route me to root url but to download a nonexistent file.

Thank you.

**Comment by RblSb** [comment]
Thanks, i think this should be fixed now.
