### ISSUE TITLE
Support permission control for makePermanent/makeTemporary

### ISSUE THREAD

**Issue by newlix** [RblSb/SyncTube#36]
Please support  permission control for makePermanent/makeTemporary. I would like to restrict them only for the admins. Thank you very much.

**Comment by RblSb** [comment]
See `"toggleItemType"` in `default-config.json`. I also make "lock playlist" button more useful, so locked playlist cannot be changed anymore without `"lockPlaylist"` permission, exceptions are "play item", "skip video" and "rewind" (not sure about blocking these).
