### ISSUE TITLE
[Feature Request] Youtube Playlist support

### ISSUE THREAD

**Issue by inrush-overload** [RblSb/SyncTube#38]
Love your project, very cool. Could there be a way to import all videos from a YouTube playlist/channel into the SyncTube playlist?

**Comment by RblSb** [comment]
Thanks!
Yes, you can add urls like `https://youtube.com/playlist?list=PL9FiZUDVMu9tc_85frYognMOVFC_-VkSX` to synctube playlist, and it should add first 50 items from youtube playlist. You can find such urls on youtube playlist pages or on playlist "share" button in youtube apps.
You can also change that limit with `{"youtubePlaylistLimit": 50}` in `user/config.json`.
