### ISSUE TITLE
Docker setup suddenly no longer working. (server is local)

### ISSUE THREAD

**Issue by MrDj200** [RblSb/SyncTube#44]
Hi, after I updated my system, my SyncTube instance can't be reached anymore.
After restarting it, I get this in the console:
![image](https://github.com/RblSb/SyncTube/assets/5685500/2f452b9f-9175-4498-9dac-dcea6e89973c)

I changed no configs or anything. Is there a way to fix it?

**Comment by RblSb** [comment]
This only meanss that url request to `https://myexternalip.com/raw` to print external ip is failed. Is this happens consistently for you?
https://github.com/RblSb/SyncTube/blob/cdf7f00f613d636e587b7840ec8b263017513486/src/server/Utils.hx#L62

**Comment by RblSb** [comment]
Okay, probably simple connection error, can happen with any website for me at some point. If this will happen again consistently, we can reopen this
