### ISSUE TITLE
streamable

### ISSUE THREAD

**Issue by 89891383** [RblSb/SyncTube#49]
Hi, I have a suggestion to add streamable.com links to synctube, is there a chance?

**Comment by 89891383** [comment]
and.. how i can add video.js player to synctube?

**Comment by RblSb** [comment]
Seems like you can copy mp4 links from that service if you pay for some plan. But i also tested, and you can use browser devtools to extract mp4 link and add it to synctube playlist. This is also possible on Android with custom browser app, i described how to do ot here. Devtools approach needs some skills from you, but maybe you will understand it.

See post https://github.com/RblSb/SyncTube/issues/46#issuecomment-1824273067

**Comment by RblSb** [comment]
About video.js, i tested this library previously and probably can add it as addon. But I don't know why you want it instead of native browser. I think video.js is not much better and their ui is too small on touch devices for example.

**Comment by RblSb** [comment]
I'm also thinking about adding feature to upload files right on synctube server with some cache folder limit and stream from it. In theory you will not be required to wait for full upload, but it will require more motivation to mess with ui side of such feature someday

**Comment by 89891383** [comment]
I prefer video.js because it seems to me more transparent and convenient. If you would add such a plugin, I would be very grateful. As for streamable, there is something on one such site that when you add a link to streamable, it automatically extracts the mp4 from that link and simply plays the video as mp4 in synchronized viewing. Cool if you could add such a feature, I would be happy to support your job.
