### ISSUE TITLE
"Video Unavailable" error on Youtube videos

### ISSUE THREAD

**Issue by ffd000** [RblSb/SyncTube#56]
When I add any Youtube video it hits me with "video unavailable" and won't play it. It's a new change.

**Comment by RblSb** [comment]
Works for me. Can you provide youtube url example?

**Comment by ffd000** [comment]
Correction: it doesn't happen with every video, but many music-related videos I try give "Video unavailable. Watch on Youtube"

> Works for me. Can you provide youtube url example?

https://www.youtube.com/watch?v=P9HjbqMIZTA
https://www.youtube.com/watch?v=LCtfLb1Vsxk
https://www.youtube.com/watch?v=-Wq9MYPVYIQ

None of these play for me.

**Comment by RblSb** [comment]
This is a limitation from the YouTube player. It does not allow embedding some videos when accessing from the server via an IP address instead of a domain. You can add any domain to your server and this error should disappear when accessing synctube through it.

**Comment by ffd000** [comment]
Oh, I am indeed accessing it via direct IP. Thank you for your help!
